spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  registry:
#    address: zookeeper://101.126.19.236:2181
    address: nacos://101.126.19.236:8848
    timeout: 50000
    parameters:
      blockUntilConnectedWait:
        50
  protocol:
    name: dubbo
    port: 20880
