spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn_jpa?serverTimezone=CST
    username: root
    password: 


  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE