dubbo:
  application:
    name: dubbo-consumer
  registry:
    #    address: zookeeper://127.0.0.1:2181
    address: nacos://127.0.0.1:8848
    timeout: 50000
    parameters:
      blockUntilConnectedWait:
        50
  protocol:
    name: dubbo
    port: 20881